[package]
name = "easter-quest"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.15.5"
axum = "0.8.8"
axum-extra = { version = "0.12.5", features = ["cookie"] }
log = "0.4.29"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-rustls", "postgres", "uuid"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.8", features = ["fs", "timeout", "trace"] }
tracing-subscriber = "0.3.23"
uuid = { version = "1.22.0", features = ["serde", "v4"] }
