---
services:
  server:
    build:
      context: .
      target: final
    secrets:
      - source: db-password
        uid: "10001"
        gid: "10001"
        mode: 0400
    ports:
      - ${HOST}:${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - ${PGPORT}:${PGPORT}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:

secrets:
  db-password:
    environment: DB_PASSWORD_FILE_CONTENTS
